### ISSUE TITLE
I run your code but it returns error

### ISSUE THREAD

**Issue by newmrxu** [zellwk/crud-demo#2]
Error: ENOENT: no such file or directory, open './secrets/variables.env'. Seems we can't find folder "secrets", what can we do?

![Snipaste_2020-06-25_16-48-10](https://user-images.githubusercontent.com/62363087/85688001-f287ea80-b703-11ea-8cd7-e6ab5e68ad04.png)

**Comment by zellwk** [comment]
This article will help you understand this environment variable file. https://zellwk.com/blog/environment-variables/
GitHub <notifications@github.com> wrote:
“Error: ENOENT: no such file or directory, open './secrets/variables.env'. Seems we can't find folder "secrets", what can we do?”


[Snipaste_2020-06-25_16-48-10]
“ —
